apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rateflow

resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/component: cache
  app.kubernetes.io/part-of: rateflow
