apiVersion: v1
kind: Service
metadata:
  name: rateflow-api
  namespace: rateflow
  labels:
    app: rateflow-api
spec:
  type: ClusterIP
  selector:
    app: rateflow-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
