apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rateflow

resources:
  - api-deployment.yaml
  - api-service.yaml

images:
  - name: tyokyo320/rateflow-api
    newTag: v1.5.0  # Change this to your desired image tag
