apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rateflow

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: tyokyo320/rateflow-web
    newTag: latest

commonLabels:
  app: rateflow
  component: web
