apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rateflow

resources:
  - worker-cronjob.yaml
  - worker-cronjob-jpy-usd.yaml

images:
  - name: tyokyo320/rateflow-worker
    newTag: v1.0.0  # Change this to your desired image tag
