apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rateflow

resources:
  - pvc.yaml
  - service.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: rateflow
